service: sls

custom:
  settings:
    POSTS_TABLE: posts

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}'

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: /users
          method: post
  getAllUsers:
    handler: handler.getAllUsers
    events:
      - http:
          path: /users
          method: get
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: /users/{number}
          method: get
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: /users/{id}
          method: put
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: /users/{id}
          method: delete

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}
